//
//  MediaResource.swift
//  CoreUI
//
//  Created by BADR  QABA on 2026-02-16.
//

public struct MediaResource {
    public static let addFileSvgrepoCom = "add-file-svgrepo-com"
    public static let addUserSvgrepoCom = "add-user-svgrepo-com"
    public static let analyticsReportSvgrepoCom = "analytics-report-svgrepo-com"
    public static let arrowLeftSvgrepoCom = "arrow-left-svgrepo-com"
    public static let attachment2SvgrepoCom = "attachment-2-svgrepo-com"
    public static let bell = "bell"
    public static let checkCircle = "check-circle"
    public static let checkMarkButtonSvgrepoCom = "check-mark-button-svgrepo-com"
    public static let cldCloudNetworkFolderSvgrepoCom = "cld-cloud-network-folder-svgrepo-com"
    public static let closeCircle = "close-circle"
    public static let closeRoundSvgrepoCom = "close-round-svgrepo-com"
    public static let contentSvgrepoCom = "content-svgrepo-com"
    public static let dashboardAltSvgrepoCom = "dashboard-alt-svgrepo-com"
    public static let delete = "delete"
    public static let documentOpenSvgrepoCom = "document-open-svgrepo-com"
    public static let documentSvgrepoCom = "document-svgrepo-com"
    public static let doorKeyPasswordSvgrepoCom = "door-key-password-svgrepo-com"
    public static let downloadSvgrepoCom = "download-svgrepo-com"
    public static let editDrawSvgrepoCom = "edit-draw-svgrepo-com"
    public static let editPenWriteSvgrepoCom = "edit-pen-write-svgrepo-com"
    public static let editSvgrepoCom = "edit-svgrepo-com"
    public static let emailOutline = "email-outline"
    public static let emptyDrawerSvgrepoCom = "empty-drawer-svgrepo-com"
    public static let errorSvgrepoCom = "error-svgrepo-com"
    public static let eyeClosed = "eye-closed"
    public static let eye = "eye"
    public static let fileUpload = "file_upload"
    public static let fileUploadIdle = "file_upload_idle"
    public static let fileAddPlusSvgrepoCom = "file-add-plus-svgrepo-com"
    public static let fileLockAltSvgrepoCom = "file-lock-alt-svgrepo-com"
    public static let filePart2SvgrepoCom = "file-part-2-svgrepo-com"
    public static let garbageTrashSvgrepoCom = "garbage-trash-svgrepo-com"
    public static let gearFileSvgrepoCom = "gear-file-svgrepo-com"
    public static let graphSvgrepoCom = "graph-svgrepo-com"
    public static let guiUserLockSvgrepoCom = "gui-user-lock-svgrepo-com"
    public static let home = "home"
    public static let informationHelpSvgrepoCom = "information-help-svgrepo-com"
    public static let information = "information"
    public static let jpgSvgrepoCom = "jpg-svgrepo-com"
    public static let labelSvgrepoCom = "label-svgrepo-com"
    public static let lock = "lock"
    public static let login = "login"
    public static let logoutColoredSvgrepoCom = "logout-colored-svgrepo-com"
    public static let logoutSvgrepoCom = "logout-svgrepo-com"
    public static let magnify = "magnify"
    public static let menu = "menu-svgrepo-com"
    public static let maximizeExpandSvgrepoCom = "maximize-expand-svgrepo-com"
    public static let maximizeSquareSvgrepoCom = "maximize-square-svgrepo-com"
    public static let minimizeSvgrepoCom = "minimize-svgrepo-com"
    public static let moonWaningCrescent = "moon-waning-crescent"
    public static let noNotifications = "no_notifications"
    public static let noReports = "no_reports"
    public static let noSupportDocuments = "no_support_documents"
    public static let noUsers = "no_users"
    public static let palette = "palette"
    public static let passwordColoredSvgrepoCom = "password-colored-svgrepo-com"
    public static let passwordSvgrepoCom = "password-svgrepo-com"
    public static let pdfSvgrepoCom = "pdf-svgrepo-com"
    public static let pictureImageSvgrepoCom = "picture-image-svgrepo-com"
    public static let pngSvgrepoCom = "png-svgrepo-com"
    public static let reportSvgrepoCom = "report-svgrepo-com"
    public static let searchAmico = "Search-amico"
    public static let splashscreenBackground = "splashscreen_background"
    public static let tag = "tag"
    public static let twoFactorAuthenticationAmico = "Two-factor-authentication-amico"
    public static let userSvgrepoCom = "user-svgrepo-com"
    public static let usersSvgrepoCom = "users-svgrepo-com"
    public static let warningSvgrepoCom = "warning-svgrepo-com"
    public static let whiteBalanceSunny = "white-balance-sunny"
    public static let airport = "airport-bold-svgrepo-com"
    public static let impact = "impact-point-svgrepo-com"
    public static let view = "view-svgrepo-com"
    public static let calendar = "calendar-5-svgrepo-com"
    public static let calendarUpdate = "calendar-8-svgrepo-com"
    public static let statusHealth = "status-health-svgrepo-com"
    public static let timeClockDate = "time-clock-date-time-icon-svgrepo-com"
    public static let solution = "problem-solver-solution-problem-solving-skill-svgrepo-com"
    public static let reportProgress = "file-files-and-folders-svgrepo-com"
    public static let envelop = "envolope"
    public static let gear = "gear"
    public static let messaging = "messaging"
    public static let privacy = "privacy"
    public static let shield = "shield"
    public static let star = "star"
    public static let chevronDown = "chevron-down-svgrepo-com"
    public static let bellColored = "bell-svgrepo-com"
    public static let paletteColored = "gui-palette-svgrepo-com"
    public static let menuVerticalDots = "menu-vertical-svgrepo-com (1)"
}
